on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out repository under GitHub workspace
      # https://github.com/actions/checkout
      - uses: actions/checkout@v2
        # Step's name
      - name: Use Node.js
        # Configures the node version used on GitHub-hosted runners
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v1
        # The Node.js version to configure
      - name: npm install, build
        # Install and build project
        run: |
          make install
          make build
        # Add environment variables
        env:
          CI: true
      - name: Run linter
        # Run Linter
        run: |
          make lint
      - name: Test & publish code coverage
        # Publish code coverage on Code Climate
        # https://github.com/paambaati/codeclimate-action
        uses: paambaati/codeclimate-action@v2.4.0
        # Add Code Climate secret key
        env:
          CC_TEST_REPORTER_ID: e1b4d691454a76b8175433616e146fa909a27dc9bc1f2664cdd22d322bd99afe
        with:
          coverageCommand: make test-coverage
          debug: true
