on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run linter
        run: |
          make install
          make lint
          make build
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.5.6
        env:
          CC_TEST_REPORTER_ID: e1b4d691454a76b8175433616e146fa909a27dc9bc1f2664cdd22d322bd99afe
        with:
          coverageCommand: make test-coverage
